// questions.js - baza pytań BrakarzAppka (PN-D-94021:2013-10)
// img: nazwa pliku bez rozszerzenia → assets/images/<img>.jpg

const ALL_Q = [
{cat:'A',q:'Czego dotyczy norma PN-D-94021:2013-10?',
 opts:['Tarcicy konstrukcyjnej iglastej sortowanej metodami wytrzymałościowymi','Tarcicy liściastej sortowanej wizualnie','Drewna okrągłego iglastego budowlanego','Wyrobów z drewna klejonego warstwowo'],
 ans:0,exp:'Norma dotyczy tarcicy konstrukcyjnej iglastej (obrzyna, szorstkiej lub struganej) z sosny, świerka, modrzewia, jodły lub daglezji, przeznaczonej na nośne konstrukcje drewniane.'},
{cat:'A',q:'Który gatunek drewna iglastego NIE jest objęty normą PN-D-94021?',
 opts:['Jodła pospolita (Abies alba)','Dąb szypułkowy (Quercus robur)','Modrzew europejski (Larix decidua)','Daglezja zielona (Pseudotsuga menziesii)'],
 ans:1,exp:'Norma obejmuje: sosnę (PNSY), świerk (PCAB), modrzew (LADC), jodłę (ABAL) i daglezję (PSMN). Dąb jest gatunkiem liściastym i nie jest objęty.'},
{cat:'A',q:'Jaki skrót gatunkowy odpowiada sośnie zwyczajnej (Pinus sylvestris)?',
 opts:['PCAB','LADC','PNSY','ABAL'],
 ans:2,exp:'PNSY = Pinus sylvestris (sosna zwyczajna). PCAB = świerk, LADC = modrzew, ABAL = jodła, PSMN = daglezja.'},
{cat:'A',q:'Jaki skrót gatunkowy odpowiada modrzewiowi europejskiemu (Larix decidua)?',
 opts:['PCAB','PSMN','PNSY','LADC'],
 ans:3,exp:'LADC = Larix decidua Mill. (modrzew europejski). PSMN = Pseudotsuga menziesii (daglezja zielona).'},
{cat:'A',q:'Jak klasyfikuje się tarcicę ze względu na wilgotność?',
 opts:['Sucha (≤ 20%) i mokra (> 20%)','Sucha (< 15%) i mokra (≥ 15%)','Sucha, półsucha i mokra','Klasy KW1, KW2, KW3'],
 ans:0,exp:'Tarcicę dzieli się na suchą (≤ 20% wilgotności) i mokrą (> 20% wilgotności). Zaleca się nie przekraczać 20% przy sortowaniu wizualnym.'},
{cat:'A',q:'Jak klasyfikuje się tarcicę o grubości b = 35 mm i stosunku h/b = 3,0?',
 opts:['Deska','Bale','Łata','Krawędziak'],
 ans:0,exp:'Tablica 1: Deski: 22 ≤ b < 50 mm I h/b ≥ 2. Grubość 35 mm ∈ [22, 50) i h/b = 3,0 ≥ 2 → deska.'},
{cat:'A',q:'Jak klasyfikuje się tarcicę o grubości b = 70 mm i stosunku h/b = 1,5?',
 opts:['Bale','Łata','Krawędziak','Belka'],
 ans:1,exp:'Tablica 1: Łaty: 30 ≤ b < 100 mm I 1 ≤ h/b < 2. Grubość 70 ∈ [30, 100) i h/b = 1,5 ∈ [1, 2) → łata.'},
{cat:'A',q:'Jak klasyfikuje się tarcicę o grubości b = 120 mm i stosunku h/b = 1,3?',
 opts:['Łata','Krawędziak','Belka','Bale'],
 ans:1,exp:'Tablica 1: Krawędziaki: b ≥ 100 mm I 1 ≤ h/b < 2. Grubość 120 ≥ 100 i h/b = 1,3 ∈ [1, 2) → krawędziak.'},
{cat:'A',q:'Jak klasyfikuje się tarcicę o grubości b = 200 mm i stosunku h/b = 2,5?',
 opts:['Krawędziak','Bale','Belka','Łata'],
 ans:2,exp:'Tablica 1: Belki: b ≥ 100 mm I h/b ≥ 2. Grubość 200 ≥ 100 i h/b = 2,5 ≥ 2 → belka.'},
{cat:'A',q:'Jakie klasy jakości wyróżnia norma przy sortowaniu metodą wizualną?',
 opts:['KW, KS, KG','KA, KB, KC','K1, K2, K3','KV, KN, KO'],
 ans:0,exp:'Przy sortowaniu wizualnym wyróżnia się: KW (klasa wyborowa), KS (klasa średniej jakości), KG (klasa gorszej jakości).'},
{cat:'A',q:'Co to jest "przekrój poprzeczny najgorszy"?',
 opts:['Przekrój w miejscu największego skupienia wad, zwłaszcza sęków','Przekrój o najmniejszej powierzchni','Przekrój przy czole tarcicy','Przekrój z najgłębszym pęknięciem'],
 ans:0,exp:'Pkt 3.3: przekrój poprzeczny najgorszy to przekrój umowny poprowadzony w miejscu największego skupienia wad drewna (zwłaszcza sęków), stanowiący płaszczyznę rzutowania tych sęków.'},
{cat:'A',q:'Jaka jest szerokość strefy marginalnej?',
 opts:['1/4 szerokości płaszczyzny tarcicy','1/3 szerokości płaszczyzny','1/2 szerokości płaszczyzny','Szerokość dowolna, wg oceny brakarza'],
 ans:0,exp:'Pkt 3.2: strefa marginalna to strefa boczna o szerokości równej ¼ szerokości płaszczyzny, na całej długości każdego z boków tarcicy.'},
{cat:'A',q:'Co oznacza skrót USM?',
 opts:['Wskaźnik sękatości strefy marginalnej (gorszy margines)','Ogólny wskaźnik sękatości','Ukośny skręt marginalny','Udział sęków martwych'],
 ans:0,exp:'USM (pkt 3.5) = wskaźnik sękatości strefy marginalnej. Odnosi się do tej z dwóch stref marginalnych, w której sęki zajmują większą powierzchnię ("gorszy margines").'},
{cat:'A',q:'Co oznacza skrót USC?',
 opts:['Ogólny wskaźnik sękatości całego przekroju','Wskaźnik sękatości strefy centralnej','Ukośny skręt czoła','Wskaźnik sęków czołowych'],
 ans:0,exp:'USC (pkt 3.6) = ogólny wskaźnik sękatości. Odnosi się do całego przekroju poprzecznego tarcicy (nie tylko strefy marginalnej).'},
{cat:'B',q:'Jakie są dopuszczalne wskaźniki USM i USC dla klasy KW?',img:'fig_a1_a2',
 opts:['USM ≤ 1/4, USC ≤ 1/4','USM ≤ 1/3, USC ≤ 1/3','USM ≤ 1/2, USC ≤ 1/4','USM ≤ 1/4, USC ≤ 1/2'],
 ans:0,exp:'Klasa KW (wyborowa): USM ≤ ¼ i USC ≤ ¼. To najsurowsze wymagania spośród wszystkich klas.'},
{cat:'B',q:'Jakie są wskaźniki sękatości dla klasy KS wariant 1?',
 opts:['USM ≤ 1/4, USC ≤ 1/3','USM ≤ 1/2, USC ≤ 1/4','USM ≤ 1/4, USC ≤ 1/4','USM ≤ 1/3, USC ≤ 1/2'],
 ans:0,exp:'KS wariant 1: USM ≤ ¼, USC ≤ ⅓. Wariant 2 dopuszcza USM ≤ ½ przy USC ≤ ¼.'},
{cat:'B',q:'Jakie są wskaźniki sękatości dla klasy KS wariant 2?',
 opts:['USM ≤ 1/2, USC ≤ 1/4','USM ≤ 1/4, USC ≤ 1/3','USM ≤ 1/2, USC ≤ 1/2','USM ≤ 1/3, USC ≤ 1/3'],
 ans:0,exp:'KS wariant 2: USM ≤ ½, USC ≤ ¼. Dopuszcza większy wskaźnik strefy marginalnej przy węższym ogólnym wskaźniku sękatości.'},
{cat:'B',q:'Jakie są wskaźniki sękatości dla klasy KG wariant 1?',img:'fig_a3',
 opts:['USM ≤ 1/2, USC ≤ 1/2','USM > 1/2, USC ≤ 1/3','USM ≤ 1/4, USC ≤ 1/4','USM ≤ 1/3, USC ≤ 1/2'],
 ans:0,exp:'KG wariant 1: USM ≤ ½, USC ≤ ½. Wariant 2 dopuszcza USM > ½ przy USC ≤ ⅓.'},
{cat:'B',q:'Jaki jest dopuszczalny ukośny przebieg włókien dla klasy KW?',img:'fig_a4',
 opts:['≤ 7% (1:14)','≤ 10% (1:10)','≤ 16% (1:6)','≤ 5% (1:20)'],
 ans:0,exp:'KW: ukośny przebieg włókien ≤ 7%, proporcja BC:AC = 1:14. KS: ≤ 10% (1:10). KG: ≤ 16% (1:6).'},
{cat:'B',q:'Jaki jest dopuszczalny ukośny przebieg włókien dla klasy KS?',
 opts:['≤ 10% (1:10)','≤ 7% (1:14)','≤ 16% (1:6)','≤ 12% (1:8)'],
 ans:0,exp:'KS: ukośny przebieg włókien ≤ 10% (1:10). Mierzy się odchylenie włókien od osi podłużnej tarcicy.'},
{cat:'B',q:'Jaki jest dopuszczalny ukośny przebieg włókien dla klasy KG?',
 opts:['≤ 16% (1:6)','≤ 10% (1:10)','≤ 20% (1:5)','Brak ograniczeń'],
 ans:0,exp:'KG: ukośny przebieg włókien ≤ 16% (proporcja 1:6). To stosunkowo luźne kryterium dla klasy gorszej.'},
{cat:'B',q:'Jakim narzędziem wykrywa się ukośny przebieg włókien?',
 opts:['Rysakiem z obrotowym uchwytem i cienką igłą','Suwmiarką elektroniczną','Szczelniomierzem','Wilgotnościomierzem'],
 ans:0,exp:'Pkt A.2: wykrywać należy rysakiem zaopatrzonym w obrotowy uchwyt i cienką igłę. Igła zagłębia się w drewno i jej ruch wzdłuż tarcicy wyznacza przebieg włókien.'},
{cat:'B',q:'Jaka jest minimalna gęstość tarcicy klasy KW przy wilgotności 20%?',
 opts:['≥ 450 kg/m³','≥ 420 kg/m³','≥ 400 kg/m³','≥ 380 kg/m³'],
 ans:0,exp:'Gęstość min. przy 20% wilgotności: KW ≥ 450 kg/m³, KS ≥ 420 kg/m³, KG ≥ 400 kg/m³ (Tablica 2).'},
{cat:'B',q:'Jaka jest minimalna gęstość tarcicy klasy KS przy wilgotności 20%?',
 opts:['≥ 420 kg/m³','≥ 450 kg/m³','≥ 400 kg/m³','≥ 440 kg/m³'],
 ans:0,exp:'KS: gęstość ≥ 420 kg/m³. Kryterium gęstości pomija się, gdy spełnione jest kryterium słoistości.'},
{cat:'B',q:'Kiedy kryterium gęstości NIE bierze się pod uwagę?',
 opts:['Gdy spełnione jest kryterium słoistości','Gdy tarcica jest mokra (>20%)','Gdy tarcica to daglezja','Zawsze — gęstość zawsze sprawdzamy'],
 ans:0,exp:'Tablica 2 (przypis c): gęstości nie bierze się pod uwagę, jeżeli spełnione jest kryterium słoistości. Słoistość i gęstość są alternatywnymi kryteriami oceny.'},
{cat:'C',q:'Jaka jest dopuszczalna głębokość pęknięć głębokich dla klasy KW?',img:'fig_a5',
 opts:['1/3 grubości sztuki','1/2 grubości sztuki','2/3 grubości sztuki','1/4 grubości sztuki'],
 ans:0,exp:'Tablica 2: pęknięcia głębokie nieprzechodzące na czoła: KW → ⅓ grubości, KS → ½ grubości, KG → ⅔ grubości.'},
{cat:'C',q:'Jaka jest maksymalna długość pęknięć głębokich dla klas KW i KS?',
 opts:['Do 1/4 długości sztuki i nie dłuższe niż 600 mm','Do 1/4 długości sztuki i nie dłuższe niż 900 mm','Do 1/3 długości sztuki i nie dłuższe niż 600 mm','Do 1/2 długości sztuki'],
 ans:0,exp:'Tablica 2: pęknięcia głębokie dopuszczalne do ¼ długości sztuki i nie dłuższe niż 600 mm — dla KW i KS. Dla KG limit długości wynosi 900 mm.'},
{cat:'C',q:'Jaka jest maksymalna długość pęknięć głębokich dla klasy KG?',
 opts:['Do 1/4 długości sztuki i nie dłuższe niż 900 mm','Do 1/4 długości i max 600 mm','Do 1/3 długości sztuki','Do 1/2 szerokości sztuki'],
 ans:0,exp:'KG: pęknięcia głębokie do ¼ długości sztuki i nie dłuższe niż 900 mm. Różnica wobec KW/KS — dłuższy limit 900 mm zamiast 600 mm.'},
{cat:'C',q:'Jak oblicza się miarę pęknięcia (p)?',
 opts:['p = G/b (głębokość G do grubości b)','p = G/h (głębokość do szerokości)','p = L/b (długość do grubości)','p = G × b'],
 ans:0,exp:'Pkt A.3: miara pęknięcia p = G/b, gdzie G = głębokość pęknięcia mierzona szczelinomierzem, b = grubość tarcicy.'},
{cat:'C',q:'Czym mierzy się głębokość pęknięcia wg normy?',
 opts:['Szczelinomierzem (płytka 0,2 mm)','Suwmiarką','Rysakiem','Taśmą mierniczą'],
 ans:0,exp:'Pkt A.3: głębokość pęknięcia mierzy się szczelinomierzem — grubość płytki mierniczej 0,2 mm.'},
{cat:'C',q:'Dopuszczalna długość pęknięć czołowych dla klasy KG:',
 opts:['Do 1½ szerokości sztuki','Do 1/1 szerokości sztuki','Do 1/2 szerokości sztuki','Pęknięcia czołowe są niedopuszczalne'],
 ans:0,exp:'Tablica 2: pęknięcia czołowe (nieprzechodzące, przechodzące i okrężne) dopuszczalne do 1/1 szerokości dla KW/KS, a do 1½ szerokości dla KG.'},
{cat:'C',q:'Czy zgnilizna jest dopuszczalna w klasie KG?',
 opts:['Nie — zgnilizna jest niedopuszczalna we wszystkich klasach','Tak — do 5% powierzchni','Tak — sinizna, nie zgnilizna','Tak — w stopniu ograniczonym'],
 ans:0,exp:'Tablica 2: zgnilizna jest niedopuszczalna we wszystkich klasach (KW, KS, KG). To bezwzględny dyskwalifikator.'},
{cat:'C',q:'Czy chodniki owadzie są dopuszczalne w jakiejkolwiek klasie?',
 opts:['Nie — chodniki owadzie są niedopuszczalne we wszystkich klasach','Tak — w klasie KG','Tak — o średnicy < 3 mm','Tak — w KS i KG'],
 ans:0,exp:'Tablica 2: chodniki owadzie są niedopuszczalne we wszystkich klasach. Są bezwzględnym dyskwalifikatorem obok zgnilizny.'},
{cat:'C',q:'Czy sinizna jest dopuszczalna wg normy?',
 opts:['Tak — dopuszczalna we wszystkich klasach','Nie — jest bezwzględnie niedopuszczalna','Tak — tylko w klasie KG','Tak — w KS i KG'],
 ans:0,exp:'Tablica 2: sinizna jest dopuszczalna we wszystkich klasach jakości. Nie dyskwalifikuje sztuki.'},
{cat:'C',q:'Jaki jest dopuszczalny udział drewna reakcyjnego w klasie KW?',img:'fig_a9',
 opts:['Do 1/5 obwodu','Do 2/5 obwodu','Do 3/5 obwodu','Niedopuszczalne'],
 ans:0,exp:'Tablica 2: drewno reakcyjne: KW → do 1/5 obwodu, KS → do 2/5 obwodu, KG → do 3/5 obwodu.'},
{cat:'C',q:'Jak oblicza się udział drewna reakcyjnego R?',
 opts:['R = (R1+R2+R3+R4) / 2(b+h)','R = największe R / (b×h)','R = (R1+R2) / b','R = (R1+R2+R3+R4) / (b+h)'],
 ans:0,exp:'Pkt A.7 i Rys. A.9: R = (R1+R2+R3+R4) / 2(b+h), gdzie R1-R4 to szerokości drewna reakcyjnego na czterech powierzchniach, b i h to wymiary przekroju.'},
{cat:'C',q:'Jaka jest dopuszczalna słoistość dla klasy KW?',img:'fig_a6',
 opts:['≤ 4 mm','≤ 6 mm','≤ 8 mm','≤ 10 mm'],
 ans:0,exp:'Tablica 2: słoistość: KW ≤ 4 mm, KS ≤ 6 mm, KG ≤ 10 mm. Mierzona jako przeciętna szerokość przyrostów rocznych.'},
{cat:'C',q:'Jaka jest dopuszczalna słoistość dla klasy KG?',
 opts:['≤ 10 mm','≤ 4 mm','≤ 6 mm','≤ 8 mm'],
 ans:0,exp:'KG: słoistość ≤ 10 mm. Pomiar wykonuje się na czole tarcicy na odcinku ok. 75 mm wzdłuż linii promieniowej.'},
{cat:'D',q:'Jak oblicza się wskaźnik obliny na płaszczyźnie jednej krawędzi?',img:'fig_a7',
 opts:['n_H = H/h','n_H = H×h','n_H = h/H','n_H = (H1+H2)/h'],
 ans:0,exp:'Pkt A.5, Rys. A.7a: wskaźnik obliny na płaszczyźnie (jedna krawędź) n_H = H/h, gdzie H = szerokość obliny, h = szerokość tarcicy.'},
{cat:'D',q:'Jaka jest dopuszczalna oblina dla klas KW i KS (łącznie na dwóch krawędziach)?',
 opts:['Do 1/4 grubości i do 1/4 szerokości','Do 1/3 grubości i do 1/3 szerokości','Do 1/2 grubości i do 1/4 szerokości','Oblina jest niedopuszczalna'],
 ans:0,exp:'Tablica 3: KW i KS oblina do ¼ grubości i do ¼ szerokości sztuki (łącznie na dwóch krawędziach jednej płaszczyzny lub boku).'},
{cat:'D',q:'Jaka jest dopuszczalna krzywizna podłużna płaszczyzyn dla klas KW i KS?',img:'fig_a8',
 opts:['≤ 10 mm (na odcinku 2 m)','≤ 8 mm','≤ 20 mm','≤ 5 mm'],
 ans:0,exp:'Tablica 3: krzywizna podłużna płaszczyzyn (Rys. A.8a): KW i KS ≤ 10 mm, KG ≤ 20 mm. Mierzona na odcinku 2 m.'},
{cat:'D',q:'Jaka jest dopuszczalna krzywizna podłużna boków dla klasy KG?',
 opts:['≤ 12 mm (na odcinku 2 m)','≤ 8 mm','≤ 20 mm','≤ 10 mm'],
 ans:0,exp:'Tablica 3: krzywizna podłużna boków: KW i KS ≤ 8 mm, KG ≤ 12 mm. Mierzona na odcinku 2 m.'},
{cat:'D',q:'Jaka jest dopuszczalna wichrowatość dla klas KW i KS?',
 opts:['≤ 1 mm/25 mm','≤ 2 mm/25 mm','≤ 0,5 mm/25 mm','≤ 5 mm/25 mm'],
 ans:0,exp:'Tablica 3: wichrowatość (Rys. A.8c): KW i KS ≤ 1 mm/25 mm, KG ≤ 2 mm/25 mm. Mierzona na odcinku 2 m.'},
{cat:'D',q:'Jaka jest dopuszczalna krzywizna poprzeczna dla klasy KG?',
 opts:['≤ 2 mm/25 mm','≤ 1 mm/25 mm','≤ 3 mm/25 mm','≤ 0,5 mm/25 mm'],
 ans:0,exp:'Tablica 3: krzywizna poprzeczna (Rys. A.8d): KW i KS ≤ 1 mm/25 mm, KG ≤ 2 mm/25 mm. Mierzona na czole tarcicy.'},
{cat:'D',q:'Na jakim odcinku mierzy się krzywiznę podłużną i wichrowatość?',
 opts:['Na odcinku 2 m','Na odcinku 1 m','Na całej długości','Na odcinku 75 mm'],
 ans:0,exp:'Pkt A.6: krzywizna podłużna płaszczyzyn, boków i wichrowatość mierzone są na odcinku o długości 2 m.'},
{cat:'D',q:'Na jakim odcinku i wzdłuż jakiej linii mierzy się słoistość?',
 opts:['Na odcinku ok. 75 mm, wzdłuż linii promieniowej na czole','Na całym czole','Na odcinku 100 mm, wzdłuż osi podłużnej','Na odcinku 50 mm, dowolna linia'],
 ans:0,exp:'Pkt A.4: słoistość mierzona jest na czole tarcicy wzdłuż linii promieniowej, na odcinku ok. 75 mm obejmującym całkowitą liczbę przyrostów rocznych.'},
{cat:'E',q:'Jak sprawdza się gatunek drewna tarcicy?',
 opts:['Przez oględziny nieuzbrojonym okiem','Wilgotnościomierzem elektrycznym','Badaniami laboratoryjnymi','Pomiarem gęstości'],
 ans:0,exp:'Pkt 6.1: gatunek drewna sprawdza się przez oględziny nieuzbrojonym okiem.'},
{cat:'E',q:'Jaką metodą podstawową sprawdza się wilgotność tarcicy?',
 opts:['Wilgotnościomierz elektryczny (PN-EN 13183-2)','Metoda suszarkowo-wagowa (PN-EN 13183-1)','Oględziny wizualne','Pomiar gęstości'],
 ans:0,exp:'Pkt 6.2: wilgotność sprawdza się wilgotnościomierzem elektrycznym (PN-EN 13183-2). W sporze — metoda suszarkowo-wagowa (PN-EN 13183-1).'},
{cat:'E',q:'Która metoda pomiaru wilgotności stosowana jest w sporze?',
 opts:['Suszarkowo-wagowa (PN-EN 13183-1)','Wilgotnościomierz elektryczny (PN-EN 13183-2)','Metoda dielektryczna','Densytometryczna'],
 ans:0,exp:'W przypadku sporu stosuje się metodę referencyjną — suszarkowo-wagową wg PN-EN 13183-1 (suszenie w 103°C do stałej masy).'},
{cat:'E',q:'Co to jest "sztuka wadliwa"?',
 opts:['Sztuka niespełniająca choćby jednego wymagania z Rozdziału 5','Sztuka z więcej niż 3 wadami','Sztuka poniżej klasy KG','Sztuka z zgnilizną lub chodnikami'],
 ans:0,exp:'Pkt 7.1: badaną sztukę tarcicy uznaje się za wadliwą, jeżeli nie spełnia chociażby jednego z wymagań z Rozdziału 5 (postanowienia ogólne, wilgotność, wymiary, jakość).'},
{cat:'E',q:'Ile sztuk należy zbadać przy weryfikacji partii 51–90 sztuk?',
 opts:['32 sztuki','20 sztuk','50 sztuk','80 sztuk'],
 ans:0,exp:'Tablica 4: partia 51–90 sztuk → próba 32 sztuki, dopuszczalne max 2 sztuki wadliwe.'},
{cat:'E',q:'Ile sztuk wadliwych dopuszcza się w próbie przy partii 51–90?',
 opts:['2 sztuki','1 sztuka','3 sztuki','5 sztuk'],
 ans:0,exp:'Tablica 4: partia 51–90 → próba 32 → max 2 sztuki wadliwe. Przekroczenie = odrzucenie partii.'},
{cat:'E',q:'Ile sztuk należy zbadać przy weryfikacji partii 281–500 sztuk?',
 opts:['125 sztuk','80 sztuk','200 sztuk','50 sztuk'],
 ans:0,exp:'Tablica 4: partia 281–500 → próba 125 sztuk → max 8 sztuk wadliwych.'},
{cat:'E',q:'Ile sztuk próby przy partii 1201–3200?',
 opts:['315 sztuk','200 sztuk','500 sztuk','125 sztuk'],
 ans:0,exp:'Tablica 4: partia 1201–3200 → próba 315 sztuk → max 18 sztuk wadliwych. Dla partii > 3200 próba = 500 sztuk, też max 18 wadliwych.'},
{cat:'E',q:'Kiedy stosuje się kontrolę stuprocentową przy weryfikacji?',
 opts:['Gdy liczność próby ≤ 20 sztuk','Gdy partia ≤ 50 sztuk','W każdym sporze','Przy reklamacji klienta'],
 ans:0,exp:'Tablica 4 (przypis a): jeżeli liczność próby jest ≤ 20 sztuk, stosuje się kontrolę stuprocentową.'},
{cat:'E',q:'Wg jakiej normy wykonuje się oznakowanie tarcicy sortowanej wytrzymałościowo?',
 opts:['PN-EN 14081-1','PN-D-94021','PN-EN 338','PN-EN 336'],
 ans:0,exp:'Pkt 8: oznakowania tarcicy sortowanej wytrzymałościowo należy wykonać zgodnie z zasadami w PN-EN 14081-1.'},
{cat:'E',q:'Jaka jest minimalna grubość tarcicy objęta normą?',
 opts:['22 mm (wyjątkowo od 19 mm przy polu min. 2000 mm²)','15 mm','18 mm','25 mm'],
 ans:0,exp:'Pkt 5.3: minimalna grubość = 22 mm. Można stosować od 19 mm przy minimalnym polu przekroju 2000 mm².'},
{cat:'E',q:'Czy tarcicę różnych gatunków można łączyć w partii do sortowania wizualnego?',
 opts:['Nie — gatunki nie wolno mieszać, zwł. jodłowej ze świerkową','Tak — zawsze dopuszczalne','Tak — ale tylko sosnowej i świerkowej','Tak — z wyjątkiem jodłowej'],
 ans:0,exp:'Pkt 5.1: w partii do sortowania wizualnego nie należy łączyć różnych gatunków, szczególnie jodłowej ze świerkową. Przy sortowaniu maszynowym jest to dopuszczalne za zgodą stron.'},

// ── Kategoria F: Normy europejskie (EN 338, EN 1912, EN 13183-2, EN 14081-1) ──
{cat:'F',q:'Którą normę europejską stosuje się do określania klas wytrzymałości drewna?',
 opts:['PN-EN 338','PN-EN 1912','PN-EN 13183-2','PN-EN 14081-1'],
 ans:0,exp:'PN-EN 338 definiuje klasy wytrzymałości (C14–C50) dla drewna iglastego i liściastego.'},
{cat:'F',q:'Jaka klasa wytrzymałości odpowiada drewnu sosnowemu klasy wizualnej KW sortowanemu wg PN-D-94021 (Europa Środkowa)?',
 opts:['C16','C18','C24','C30'],
 ans:2,exp:'Wg PN-EN 1912, sosna zwyczajna (Pinus sylvestris) klasa S10/S10K (odpowiednik KW) → C24 dla strefy CNE.'},
{cat:'F',q:'Jaka klasa wytrzymałości odpowiada drewnu świerkowemu klasy KS?',
 opts:['C18','C24','C30','C14'],
 ans:1,exp:'Świerk pospolity (Picea abies) klasa S10/S10K → C24 wg PN-EN 1912 dla Europy Środkowej.'},
{cat:'F',q:'Jaka jest wartość charakterystycznej wytrzymałości na zginanie fm,k dla klasy C24?',
 opts:['18 MPa','20 MPa','24 MPa','30 MPa'],
 ans:2,exp:'C24 oznacza fm,k = 24 MPa. Cyfra w oznaczeniu klasy odpowiada wartości fm,k w MPa.'},
{cat:'F',q:'Jaka jest charakterystyczna gęstość ρk drewna klasy C24?',
 opts:['310 kg/m³','320 kg/m³','350 kg/m³','380 kg/m³'],
 ans:2,exp:'Wg PN-EN 338, klasa C24 ma ρk = 350 kg/m³.'},
{cat:'F',q:'W jakiej odległości od czoła tarcicy należy wbijać elektrody wilgotnościomierza oporowego wg PN-EN 13183-2?',
 opts:['Co najmniej 0,1 m','Co najmniej 0,3 m','Co najmniej 0,5 m','Co najmniej 1,0 m'],
 ans:1,exp:'Wg PN-EN 13183-2 elektrody umieszcza się w odległości ≥ 0,3 m od czoła.'},
{cat:'F',q:'Na jaką głębokość wbija się elektrody wilgotnościomierza oporowego?',
 opts:['0,1 grubości tarcicy','0,2 grubości tarcicy','0,3 grubości tarcicy','Do połowy grubości'],
 ans:2,exp:'Elektrody wbija się na głębokość 0,3 grubości (0,3t) wg PN-EN 13183-2.'},
{cat:'F',q:'Jak zaokrągla się wynik pomiaru wilgotnościomierza oporowego?',
 opts:['Do najbliższego pełnego procentu','Zawsze w dół do pełnego procentu','Zawsze w górę do pełnego procentu','Do 0,5%'],
 ans:2,exp:'Wg PN-EN 13183-2 wynik zaokrągla się zawsze w górę do pełnego procentu.'},
{cat:'F',q:'Jaki jest zakres pomiarowy wilgotnościomierza oporowego wg PN-EN 13183-2?',
 opts:['0–20%','5–25%','7–30%','10–40%'],
 ans:2,exp:'Norma PN-EN 13183-2 określa zakres stosowania metody oporowej na 7–30%.'},
{cat:'F',q:'Co oznacza litera \'V\' w oznaczeniu metody sortowania wg PN-EN 14081-1?',
 opts:['Sortowanie maszynowe (machine)','Sortowanie wizualne (visual)','Klasę wytrzymałości','Weryfikację certyfikatu'],
 ans:1,exp:'V = Visual (wizualne), M = Machine (maszynowe) — metody sortowania wg EN 14081-1.'},
{cat:'F',q:'Przez jaki czas należy przechowywać dokumentację FPC (kontrola produkcji) wg PN-EN 14081-1?',
 opts:['3 lata','5 lat','10 lat','20 lat'],
 ans:2,exp:'Dokumentacja systemu FPC (Factory Production Control) musi być przechowywana przez 10 lat.'},
{cat:'F',q:'Której klasie wytrzymałości odpowiada modrzew europejski (Larix decidua) klasy wizualnej KG (S13/S13K)?',
 opts:['C18','C24','C30','C35'],
 ans:2,exp:'Wg PN-EN 1912, modrzew europejski klasy S13/S13K odpowiada klasie wytrzymałości C30.'},
];
